# Generated by Django 3.1.6 on 2021-02-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='mac_address',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
